import type { MenuItem, Category } from "@/store/useStore";

export const menuItems: MenuItem[] = [
  // Sundaes
  {
    id: "mangonada",
    name: "Mangonada",
    nameFr: "Mangonada",
    price: 11.25,
    description: "Twist de sorbet à la mangue, compote mangue, compote fraise, fraises, bonbon tamarin, tajin, chamoy",
    category: "sundaes",
    color: "#FF8C42",
    accentColor: "#FF6B9D",
    flavorProfile: ["Mango", "Chili", "Sweet", "Tangy"],
  },
  {
    id: "le-shortcake",
    name: "Le Shortcake",
    nameFr: "Le Shortcake",
    price: 9.00,
    description: "Vanille, gâteau, compote fraise, crumble",
    category: "sundaes",
    color: "#FF6B9D",
    accentColor: "#FFF8F0",
    flavorProfile: ["Vanilla", "Strawberry", "Cake"],
  },
  {
    id: "banana-bonita",
    name: "Banana Bonita",
    nameFr: "Banana Bonita",
    price: 10.00,
    description: "Banane split, choix de sauce, choix de glace, noix",
    category: "sundaes",
    color: "#F4C430",
    accentColor: "#FF8C42",
    flavorProfile: ["Banana", "Nutty", "Caramel"],
  },
  {
    id: "le-turtle",
    name: "Le Turtle",
    nameFr: "Le Turtle",
    price: 11.00,
    description: "Vanille, sauce chocolat, caramel, pacanes, crème fouettée",
    category: "sundaes",
    color: "#8B4513",
    accentColor: "#F4C430",
    flavorProfile: ["Chocolate", "Caramel", "Pecan"],
  },
  {
    id: "isla-violette",
    name: "Isla Violette",
    nameFr: "Isla Violette",
    price: 11.00,
    description: "Twist de taro & fraise, compote à la fraise, gâteau vanille, fleurs, crème fouettée",
    category: "sundaes",
    color: "#9B59B6",
    accentColor: "#FF6B9D",
    flavorProfile: ["Taro", "Strawberry", "Floral"],
  },
  {
    id: "le-matilda",
    name: "Le Matilda",
    nameFr: "Le Matilda",
    price: 9.50,
    description: "Gâteau chocolat, fudge, sauce fudge, glace vanille ou chocolat",
    category: "sundaes",
    color: "#2C1810",
    accentColor: "#F4C430",
    flavorProfile: ["Rich Chocolate", "Fudge", "Decadent"],
  },
  // Soft Serve
  {
    id: "bloody-mangue",
    name: "Bloody Mangue",
    nameFr: "Bloody Mangue",
    price: 7.00,
    description: "Sorbet mangue et sorbet melon d'eau fraise — un twist parfait",
    category: "softserve",
    color: "#FF6B35",
    accentColor: "#FF6B9D",
    flavorProfile: ["Mango", "Watermelon", "Refreshing"],
  },
  {
    id: "nuage-violet",
    name: "Nuage Violet",
    nameFr: "Nuage Violet",
    price: 7.00,
    description: "Crème glacée vanille et crème glacée taro — un mariage céleste",
    category: "softserve",
    color: "#9B59B6",
    accentColor: "#FFF8F0",
    flavorProfile: ["Vanilla", "Taro", "Dreamy"],
  },
  {
    id: "vanille",
    name: "Vanilla",
    nameFr: "Crème Glacée Vanille",
    price: 5.50,
    description: "Notre crème glacée vanille classique en petit ou régulier",
    category: "softserve",
    color: "#FFF8E7",
    accentColor: "#F4C430",
    flavorProfile: ["Classic", "Creamy", "Pure"],
  },
  {
    id: "sorbet-mojito",
    name: "Sorbet Mojito",
    nameFr: "Sorbet Mojito",
    price: 7.00,
    description: "Sorbet mojito avec alcool 25% — rafraîchissant et festif",
    category: "softserve",
    color: "#00C9B1",
    accentColor: "#FFFFFF",
    flavorProfile: ["Mint", "Lime", "Refreshing"],
  },
  // Hard Ice Cream
  {
    id: "pistache",
    name: "Pistachio",
    nameFr: "Pistache",
    price: 5.20,
    description: "Crème glacée pistache artisanale, riche et généreuse",
    category: "hardice",
    color: "#7CB342",
    accentColor: "#F4C430",
    flavorProfile: ["Pistachio", "Nutty", "Premium"],
  },
  {
    id: "praline",
    name: "Praline",
    nameFr: "Praline",
    price: 5.20,
    description: "Praline caramelisée, une douceur irrésistible",
    category: "hardice",
    color: "#C68642",
    accentColor: "#F4C430",
    flavorProfile: ["Praline", "Caramel", "Sweet"],
  },
  {
    id: "pate-a-biscuit",
    name: "Cookie Dough",
    nameFr: "Pâte À Biscuit",
    price: 5.20,
    description: "Morceaux de pâte à biscuit dans une glace crémeuse",
    category: "hardice",
    color: "#D4A574",
    accentColor: "#8B4513",
    flavorProfile: ["Cookie Dough", "Vanilla", "Indulgent"],
  },
  // Drinks
  {
    id: "affogato",
    name: "Affogato",
    nameFr: "L'Affogato",
    price: 8.00,
    description: "Crème glacée vanille, shot d'espresso, biscuit — l'Italie rencontre le Québec",
    category: "drinks",
    color: "#2C1810",
    accentColor: "#F4C430",
    flavorProfile: ["Espresso", "Vanilla", "Italian"],
  },
  {
    id: "jarritos-float",
    name: "Jarritos Float",
    nameFr: "Le Jarritos Float",
    price: 10.00,
    description: "Crème glacée vanille, soda Jarritos, crème fouettée",
    category: "drinks",
    color: "#FF8C42",
    accentColor: "#FF6B9D",
    flavorProfile: ["Fruity", "Fizzy", "Fun"],
  },
  {
    id: "aguas-mangue",
    name: "Mango Maracuyá",
    nameFr: "Mangue Maracuyá",
    price: 7.25,
    description: "Agua fresca maison à la mangue et maracuyá, fraîcheur tropicale",
    category: "drinks",
    color: "#FF8C42",
    accentColor: "#F4C430",
    flavorProfile: ["Mango", "Passion Fruit", "Tropical"],
  },
  {
    id: "matcha",
    name: "Matcha",
    nameFr: "Matcha Latte",
    price: 5.50,
    description: "Latte matcha premium, doux et terreux",
    category: "drinks",
    color: "#7CB342",
    accentColor: "#FFF8F0",
    flavorProfile: ["Matcha", "Earthy", "Calming"],
  },
  // Churros
  {
    id: "churros-3",
    name: "3 Churros",
    nameFr: "3 Churros",
    price: 5.75,
    description: "Churros dorés et croustillants, parfaits avec notre sauce caramel ou fudge",
    category: "churros",
    color: "#D4A574",
    accentColor: "#F4C430",
    flavorProfile: ["Cinnamon", "Crispy", "Warm"],
  },
  {
    id: "churros-sundae",
    name: "Churro Sundae",
    nameFr: "Le Churro Sundae",
    price: 8.50,
    description: "2 churros, glace au choix, sauce caramel ou fudge",
    category: "churros",
    color: "#C68642",
    accentColor: "#F4C430",
    flavorProfile: ["Churro", "Ice Cream", "Caramel"],
  },
  {
    id: "beignets-6",
    name: "6 Beignets",
    nameFr: "6 Beignets",
    price: 11.00,
    description: "Beignets dorés et moelleux — une douceur nostalgique",
    category: "churros",
    color: "#F4C430",
    accentColor: "#8B4513",
    flavorProfile: ["Airy", "Sweet", "Golden"],
  },
  // Seasonal
  {
    id: "le-pumpkin",
    name: "Le Pumpkin",
    nameFr: "Le Pumpkin",
    price: 9.50,
    description: "Cupcake citrouille, fudge choco blanc, sauce chocolat blanc & épices, glace vanille ou twist choco-citrouille, crumble épices",
    category: "seasonal",
    color: "#FF8C42",
    accentColor: "#8B4513",
    flavorProfile: ["Pumpkin", "Spice", "Autumn"],
  },
  {
    id: "rosita-tres-leches",
    name: "Rosita Tres Leches",
    nameFr: "Rosita Tres Leches",
    price: 9.60,
    description: "Twist goyave taro, tres leches aux fraises maison, glace vanille, plantains frits",
    category: "seasonal",
    color: "#FF6B9D",
    accentColor: "#9B59B6",
    flavorProfile: ["Guava", "Taro", "Tropical"],
  },
  {
    id: "le-flan",
    name: "Flan Maison",
    nameFr: "Le Flan",
    price: 9.00,
    description: "Flan maison, glace vanille, sauce caramel maison, crumble maison, crème fouettée",
    category: "seasonal",
    color: "#F4C430",
    accentColor: "#C68642",
    flavorProfile: ["Caramel", "Custard", "Classic"],
  },
];

export const categoryMeta: Record<Category, { label: string; labelFr: string; emoji: string; color: string }> = {
  sundaes: { label: "Sundaes", labelFr: "Les Sundaes", emoji: "🍨", color: "#FF6B9D" },
  softserve: { label: "Soft Serve", labelFr: "Les Twists", emoji: "🍦", color: "#9B59B6" },
  hardice: { label: "Hard Ice Cream", labelFr: "Glaces Dures", emoji: "🍧", color: "#00C9B1" },
  drinks: { label: "Drinks", labelFr: "Les Boissons", emoji: "🥤", color: "#FF8C42" },
  churros: { label: "Churros & Beignets", labelFr: "Churros & Beignets", emoji: "🍩", color: "#F4C430" },
  seasonal: { label: "Seasonal", labelFr: "Spéciaux", emoji: "⭐", color: "#1A1AFF" },
};

export function getItemsByCategory(cat: Category): MenuItem[] {
  return menuItems.filter((item) => item.category === cat);
}
